import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/Navbar/Index";
import { PlayerBar } from "components/Player/PlayerBar";
const inter = Inter({ subsets: ["latin"] });
import { Header } from "components/Navbar/Header";
import { Main } from "components/Layout/Main";
import { ScrollProvider } from "app/context/ScrollContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <ScrollProvider>
        <body id="app" className={`relative p-2 gap-2 ${inter.className}`}>
          <Navbar />

          <Main>
            <Header />
            <div className="px-6 py-4 flex flex-col gap-7">{children}</div>
          </Main>
          <PlayerBar />
        </body>
      </ScrollProvider>
    </html>
  );
}
